# generated by APDR
import importlib
import io
import os
import sys
import traceback

def _load_import(name):
    try:
        importlib.import_module(name)
    except Exception:
        traceback.print_exc()
        raise

_load_import("scrapy")

globals_dict = {'__name__': '__main__'}
with io.open('snippet.py', 'r', encoding='utf-8') as handle:
    code = compile(handle.read(), 'snippet.py', 'exec')
exec(code, globals_dict)
