"""Docker build/run CLI wrappers and Dockerfile generation."""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import subprocess
import time
from pathlib import Path


def _base_system_packages(python_version: str) -> list[str]:
    packages = ["build-essential"]
    if python_version.startswith("2."):
        packages.append("python-dev")
    else:
        packages.append("python3-dev")
    packages.append("pkg-config")
    return packages


def _render_dockerfile(
    *,
    base_image: str,
    python_version: str,
    system_deps: list[str],
    environment_variables: list[str],
    working_directory: str,
    command: list[str],
) -> str:
    packages = _base_system_packages(python_version)
    for dep in system_deps:
        if dep not in packages:
            packages.append(dep)
    packages_str = " ".join(packages)

    if python_version.startswith("2.7"):
        apt_install = (
            "RUN sed -i 's|deb.debian.org/debian|archive.debian.org/debian|g' /etc/apt/sources.list "
            "&& sed -i 's|security.debian.org/debian-security|archive.debian.org/debian-security|g' /etc/apt/sources.list "
            "&& sed -i '/buster-updates/d' /etc/apt/sources.list "
            f"&& apt-get -o Acquire::Check-Valid-Until=false update "
            f"&& apt-get install -y --no-install-recommends {packages_str} "
            "&& rm -rf /var/lib/apt/lists/*"
        )
    else:
        apt_install = (
            f"RUN apt-get update && apt-get install -y --no-install-recommends {packages_str} "
            "&& rm -rf /var/lib/apt/lists/*"
        )

    env_block = "".join(f"ENV {item}\n" for item in environment_variables if item.strip())
    cmd = json.dumps(command or ["python", "/app/smoke_test.py"])

    return (
        f"# syntax=docker/dockerfile:1\n"
        f"FROM {base_image}\n"
        f"WORKDIR {working_directory or '/app'}\n"
        f"{apt_install}\n"
        f"{env_block}"
        f"COPY requirements.txt /app/requirements.txt\n"
        f"RUN --mount=type=cache,target=/root/.cache/pip "
        f"python -m pip install --upgrade pip setuptools wheel && "
        f"pip install --default-timeout=100 -r /app/requirements.txt\n"
        f"COPY smoke_test.py /app/smoke_test.py\n"
        f"COPY snippet.py /app/snippet.py\n"
        f"CMD {cmd}\n"
    )


def generate_dockerfile(python_version: str, system_deps: list[str]) -> str:
    """Generate a Dockerfile string. Mirrors templates.rs."""
    return _render_dockerfile(
        base_image=f"python:{python_version}-slim",
        python_version=python_version,
        system_deps=system_deps,
        environment_variables=[],
        working_directory="/app",
        command=["python", "/app/smoke_test.py"],
    )


def generate_dockerfile_from_plan(
    python_version: str,
    system_deps: list[str],
    docker_plan: dict | None,
) -> str:
    """Generate a Dockerfile string from an authored Docker plan when available."""
    if not docker_plan:
        return generate_dockerfile(python_version, system_deps)
    merged_system_deps = list(docker_plan.get("system_packages") or [])
    for dep in system_deps:
        if dep not in merged_system_deps:
            merged_system_deps.append(dep)
    return _render_dockerfile(
        base_image=str(docker_plan.get("base_image") or f"python:{python_version}-slim"),
        python_version=python_version,
        system_deps=merged_system_deps,
        environment_variables=[
            str(item).strip()
            for item in (docker_plan.get("environment_variables") or [])
            if str(item).strip()
        ],
        working_directory=str(docker_plan.get("working_directory") or "/app"),
        command=[str(item) for item in (docker_plan.get("command") or ["python", "/app/smoke_test.py"])],
    )


def generate_smoke_test(imports: list[str], execute_snippet: bool = False) -> str:
    lines = [
        "# generated by APDR docker_agent",
        "import importlib",
        "import traceback",
        "",
        "def _load_import(name):",
        "    try:",
        "        importlib.import_module(name)",
        "    except Exception:",
        "        traceback.print_exc()",
        "        raise",
        "",
    ]
    for imp in imports:
        lines.append(f"_load_import({imp!r})")
    if execute_snippet:
        lines += [
            "",
            "import io",
            "globals_dict = {'__name__': '__main__'}",
            "with io.open('snippet.py', 'r', encoding='utf-8') as handle:",
            "    code = compile(handle.read(), 'snippet.py', 'exec')",
            "exec(code, globals_dict)",
        ]
    else:
        lines.append("print('smoke-ok')")
    return "\n".join(lines) + "\n"


def setup_work_dir(
    output_dir: str,
    attempt_index: int,
    python_version: str,
    requirements_txt: str,
    snippet_path: str,
    imports: list[str],
    system_deps: list[str],
) -> tuple[str, str, str]:
    """Create work directory with all build files. Returns (work_dir, image_tag, container_name)."""
    work_dir = os.path.join(output_dir, f"attempt-{attempt_index}-py{python_version}")
    os.makedirs(work_dir, exist_ok=True)

    # Write build files
    with open(os.path.join(work_dir, "requirements.txt"), "w") as f:
        f.write(requirements_txt)
    with open(os.path.join(work_dir, "smoke_test.py"), "w") as f:
        f.write(generate_smoke_test(imports))
    shutil.copy2(snippet_path, os.path.join(work_dir, "snippet.py"))
    dockerfile = generate_dockerfile(python_version, system_deps)
    with open(os.path.join(work_dir, "Dockerfile"), "w") as f:
        f.write(dockerfile)

    # Image tag
    key = hashlib.sha256(f"{requirements_txt}:{python_version}".encode()).hexdigest()[:12]
    image_tag = f"apdr-agent:{key}-py{python_version}"
    container_name = f"apdr-agent-{key}-{attempt_index}"

    return work_dir, image_tag, container_name


def docker_build(
    work_dir: str, image_tag: str, timeout: int = 300
) -> dict:
    """Run docker build. Returns {success, log, exit_code, duration_ms}."""
    start = time.monotonic()
    try:
        result = subprocess.run(
            ["docker", "build", "--progress=plain", "-t", image_tag, work_dir],
            capture_output=True,
            text=True,
            timeout=timeout,
            env={**os.environ, "DOCKER_BUILDKIT": "1"},
        )
        elapsed_ms = int((time.monotonic() - start) * 1000)
        log = result.stdout + "\n" + result.stderr
        return {
            "success": result.returncode == 0,
            "log": log,
            "exit_code": result.returncode,
            "duration_ms": elapsed_ms,
            "timed_out": False,
        }
    except subprocess.TimeoutExpired:
        elapsed_ms = int((time.monotonic() - start) * 1000)
        return {
            "success": False,
            "log": "Docker build timed out",
            "exit_code": None,
            "duration_ms": elapsed_ms,
            "timed_out": True,
        }


def docker_run(
    image_tag: str, container_name: str, timeout: int = 120
) -> dict:
    """Run docker run. Returns {success, log, exit_code, duration_ms}."""
    start = time.monotonic()
    try:
        result = subprocess.run(
            ["docker", "run", "--rm", "--name", container_name, image_tag],
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        elapsed_ms = int((time.monotonic() - start) * 1000)
        log = result.stdout + "\n" + result.stderr
        return {
            "success": result.returncode == 0,
            "log": log,
            "exit_code": result.returncode,
            "duration_ms": elapsed_ms,
            "timed_out": False,
        }
    except subprocess.TimeoutExpired:
        elapsed_ms = int((time.monotonic() - start) * 1000)
        # Try to kill the container
        subprocess.run(["docker", "rm", "-f", container_name], capture_output=True)
        return {
            "success": False,
            "log": "Docker run timed out",
            "exit_code": None,
            "duration_ms": elapsed_ms,
            "timed_out": True,
        }
